# Support PSGC API by using the funding links below
# Created by Justin Balaguer, developed and maintained by Wareneutron Developers

custom: ['https://wareneutron.com/donate']

# Your donation means a lot to us to continue the development of open-source project like this.
