# Support PSGC API by using the funding links below
# Developed and Maintained by Justin Balaguer and Wareneutron Developers

custom: ['https://buymeacoff.ee/wareneutron']

# Your donation means a lot to us to continue the development of open-source project like this.
